const wines=[
{slug:"santa-julia-chenin-dulce",winery:"Santa Julia",name:"Dulce Natural Chenin",region:"Mendoza, Argentina",grape:"Chenin Blanc",type:"Sobremesa",rating:4.1,reviews:78,price:89.9},
{slug:"dv-catena-chardonnay",winery:"D.V. Catena",name:"Chardonnay - Chardonnay",region:"Mendoza, Argentina",grape:"Chardonnay",type:"Branco",rating:4.2,reviews:22877,price:179.9},
{slug:"dv-catena-malbec",winery:"D.V. Catena",name:"Malbec - Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:4.2,reviews:18400,price:189.9},
{slug:"santa-julia-organica-malbec",winery:"Santa Julia",name:"Orgánica Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:3.8,reviews:91,price:99.9},
{slug:"santa-julia-la-vaquita",winery:"Santa Julia",name:"La Vaquita Clarete Natural",region:"Maipú, Argentina",grape:"Blend",type:"Rosé",rating:3.8,reviews:1417,price:109.9},
{slug:"santa-julia-el-zorrito",winery:"Santa Julia",name:"El Zorrito Naranjo Chardonnay",region:"Maipú, Argentina",grape:"Chardonnay",type:"Branco",rating:3.8,reviews:2511,price:119.9},
{slug:"catena-malbec",winery:"Catena Zapata",name:"Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:4.0,reviews:9820,price:159.9},
{slug:"chandon-brut",winery:"Chandon",name:"Brut",region:"Serra Gaúcha, Brasil",grape:"Blend",type:"Espumante",rating:4.0,reviews:3480,price:149.9}
];
const money=n=>"R$ "+n.toFixed(2).replace(".",",");
const safe=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function wineCard(w,i=0){return '<article class="wine-card"><a class="wine-link" href="/vinho.html?slug='+encodeURIComponent(w.slug)+'"><div class="wine-image"><span class="badge">'+(i%3===0?"Destaque":"Videira")+'</span><div class="bottle"><span>'+safe(w.winery)+'</span></div></div><div class="rating">★ '+w.rating.toFixed(1).replace(".",",")+' <small>('+w.reviews.toLocaleString("pt-BR")+')</small></div><span class="winery">'+safe(w.winery)+'</span><h3>'+safe(w.name)+'</h3><span class="region">'+safe(w.region)+'</span><div class="price">'+money(w.price)+'</div></a><button class="quote-btn" data-slug="'+w.slug+'">Pedir orçamento</button></article>'}
function renderRail(id,list){const el=document.getElementById(id);if(el)el.innerHTML=list.map(wineCard).join("")}
renderRail("discover",wines.slice(0,7));renderRail("rated",[...wines].sort((a,b)=>b.rating-a.rating).slice(0,7));
function setupRails(){document.querySelectorAll(".rail-shell").forEach(w=>{const rail=w.querySelector(".wine-rail");if(!rail)return;w.querySelector(".prev")?.addEventListener("click",()=>rail.scrollBy({left:-520,behavior:"smooth"}));w.querySelector(".next")?.addEventListener("click",()=>rail.scrollBy({left:520,behavior:"smooth"}));let down=false,start=0,left=0;rail.addEventListener("pointerdown",e=>{down=true;start=e.clientX;left=rail.scrollLeft;rail.classList.add("dragging");rail.setPointerCapture(e.pointerId)});rail.addEventListener("pointermove",e=>{if(down)rail.scrollLeft=left-(e.clientX-start)});["pointerup","pointercancel","pointerleave"].forEach(ev=>rail.addEventListener(ev,()=>{down=false;rail.classList.remove("dragging")}))})}
function quote(slug){const w=wines.find(x=>x.slug===slug);if(!w)return;window.open("https://wa.me/?text="+encodeURIComponent("Olá! Gostaria de solicitar um orçamento para "+w.winery+" "+w.name+"."),"_blank","noopener")}
document.addEventListener("click",e=>{const b=e.target.closest(".quote-btn");if(b){e.preventDefault();quote(b.dataset.slug)}});

const catalog=document.getElementById("catalog");
function filtered(){let list=[...wines];if(!catalog)return list;const urlQ=new URLSearchParams(location.search).get("q")?.toLowerCase();if(urlQ)list=list.filter(w=>[w.name,w.winery,w.region,w.grape,w.type].join(" ").toLowerCase().includes(urlQ));const checked=[...document.querySelectorAll('.filter-block input[type="checkbox"]:checked')].map(x=>x.value);if(checked.length)list=list.filter(w=>checked.includes(w.type));const max=Number(document.getElementById("priceRange")?.value||9999);list=list.filter(w=>w.price<=max);const rat=Number(document.querySelector('input[name="rating"]:checked')?.value||0);if(rat)list=list.filter(w=>w.rating>=rat);const grape=document.getElementById("grapeSearch")?.value.toLowerCase().trim();if(grape)list=list.filter(w=>w.grape.toLowerCase().includes(grape));const sort=document.getElementById("sort")?.value;if(sort==="Menor preço")list.sort((a,b)=>a.price-b.price);if(sort==="Maior preço")list.sort((a,b)=>b.price-a.price);if(sort==="Melhor avaliação")list.sort((a,b)=>b.rating-a.rating);return list}
function renderCatalog(){if(!catalog)return;const list=filtered();catalog.innerHTML=list.map(wineCard).join("");const c=document.getElementById("resultCount");if(c)c.textContent=list.length+" vinhos encontrados"}
document.querySelectorAll(".filters input,#sort").forEach(el=>el.addEventListener("input",()=>{const pr=document.getElementById("priceRange");const pv=document.getElementById("priceValue");if(pr&&pv)pv.textContent="Até "+money(Number(pr.value));renderCatalog()}));renderCatalog();

const product=document.getElementById("product");if(product){const slug=new URLSearchParams(location.search).get("slug")||wines[0].slug;const w=wines.find(x=>x.slug===slug)||wines[0];document.title=w.winery+" "+w.name+" | Videira";const crumb=document.getElementById("crumbWine");if(crumb)crumb.textContent=w.name;product.innerHTML='<div class="product-grid"><div class="gallery"><div class="thumb active"><div class="mini"></div></div><div class="product-image"><div class="big-bottle"><span>'+safe(w.winery)+'</span></div></div></div><div class="product-info"><span class="winery">'+safe(w.winery)+'</span><h1>'+safe(w.name)+'</h1><p class="product-region">'+safe(w.region)+'</p><div class="product-rating">★ '+w.rating.toFixed(1).replace(".",",")+' <span>'+w.reviews.toLocaleString("pt-BR")+' avaliações</span></div><div class="facts"><div><b>Tipo</b><span>'+safe(w.type)+'</span></div><div><b>Uva</b><span>'+safe(w.grape)+'</span></div><div><b>Região</b><span>'+safe(w.region)+'</span></div><div><b>Produtor</b><span>'+safe(w.winery)+'</span></div></div><p class="description">Rótulo de demonstração para o catálogo Videira. Consulte disponibilidade, safra e condições comerciais no orçamento.</p><div class="product-price">'+money(w.price)+'</div><button class="quote-btn product-quote" data-slug="'+w.slug+'">Pedir orçamento</button></div></div>';renderRail("same",wines.filter(x=>x.winery===w.winery&&x.slug!==w.slug).concat(wines.filter(x=>x.winery!==w.winery)).slice(0,7))}
setupRails();
