const wines=[
{slug:"santa-julia-chenin-dulce",winery:"Santa Julia",name:"Dulce Natural Chenin",region:"Mendoza, Argentina",grape:"Chenin Blanc",type:"Sobremesa",rating:4.1,reviews:78,price:89.9,old:119,discount:24},
{slug:"dv-catena-chardonnay",winery:"D.V. Catena",name:"Chardonnay - Chardonnay",region:"Mendoza, Argentina",grape:"Chardonnay",type:"Branco",rating:4.2,reviews:22877,price:179.9,old:229,discount:21},
{slug:"dv-catena-malbec",winery:"D.V. Catena",name:"Malbec - Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:4.2,reviews:18400,price:189.9,old:249,discount:24},
{slug:"santa-julia-organica-malbec",winery:"Santa Julia",name:"Orgánica Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:3.8,reviews:91,price:99.9,old:139,discount:28},
{slug:"santa-julia-la-vaquita",winery:"Santa Julia",name:"La Vaquita Clarete Natural",region:"Maipú, Argentina",grape:"Blend",type:"Rosé",rating:3.8,reviews:1417,price:109.9,old:149,discount:26},
{slug:"santa-julia-el-zorrito",winery:"Santa Julia",name:"El Zorrito Naranjo Chardonnay",region:"Maipú, Argentina",grape:"Chardonnay",type:"Branco",rating:3.8,reviews:2511,price:119.9,old:159,discount:25},
{slug:"catena-malbec",winery:"Catena Zapata",name:"Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:4.0,reviews:9820,price:159.9,old:199,discount:20},
{slug:"chandon-brut",winery:"Chandon",name:"Brut",region:"Serra Gaúcha, Brasil",grape:"Blend",type:"Espumante",rating:4.0,reviews:3480,price:149.9,old:199,discount:25}
];
const money=n=>"R$ "+n.toFixed(2).replace(".",",");
const stars=r=>"★ "+r.toFixed(1).replace(".",",");
function card(w,i=0){return '<article class="p-card"><a href="/vinho.html?slug='+w.slug+'"><div class="p-image"><span class="discount">−'+w.discount+'%</span><div class="bottle"><span>'+w.winery+'</span></div></div><div class="p-winery">'+w.winery+'</div><h3>'+w.name+'</h3><div class="p-rating">'+stars(w.rating)+' <small>('+w.reviews.toLocaleString("pt-BR")+' classificações)</small></div><div class="p-prices"><strong>'+money(w.price)+'</strong><del>'+money(w.old)+'</del></div></a><button class="quote-btn" data-slug="'+w.slug+'">Pedir orçamento</button></article>'}
function render(id,list){const el=document.getElementById(id);if(el)el.innerHTML=list.map(card).join("")}
render("offers",wines);render("best",[...wines].sort((a,b)=>b.reviews-a.reviews));render("drops",[...wines].sort((a,b)=>b.discount-a.discount));
function setupRails(){document.querySelectorAll(".rail-wrap").forEach(w=>{const rail=w.querySelector(".product-rail");if(!rail)return;w.querySelector(".prev")?.addEventListener("click",()=>rail.scrollBy({left:-600,behavior:"smooth"}));w.querySelector(".next")?.addEventListener("click",()=>rail.scrollBy({left:600,behavior:"smooth"}));let down=false,start=0,left=0;rail.addEventListener("pointerdown",e=>{down=true;start=e.clientX;left=rail.scrollLeft;rail.classList.add("dragging");rail.setPointerCapture(e.pointerId)});rail.addEventListener("pointermove",e=>{if(down)rail.scrollLeft=left-(e.clientX-start)});["pointerup","pointercancel","pointerleave"].forEach(ev=>rail.addEventListener(ev,()=>{down=false;rail.classList.remove("dragging")}))})}
setupRails();
document.addEventListener("click",e=>{const b=e.target.closest(".quote-btn");if(!b)return;e.preventDefault();const w=wines.find(x=>x.slug===b.dataset.slug);if(!w)return;window.open("https://wa.me/?text="+encodeURIComponent("Olá! Gostaria de solicitar um orçamento para "+w.winery+" "+w.name+"."),"_blank","noopener")});
const cat=document.getElementById("catalog");
function filters(){let list=[...wines];if(!cat)return list;const q=new URLSearchParams(location.search).get("q")?.toLowerCase();if(q)list=list.filter(w=>[w.name,w.winery,w.region,w.grape,w.type].join(" ").toLowerCase().includes(q));const types=[...document.querySelectorAll('.filters-panel input[type="checkbox"]:checked')].map(x=>x.value);const wineTypes=types.filter(x=>["Tinto","Branco","Espumante","Rosé","Sobremesa","Fortificado"].includes(x));if(wineTypes.length)list=list.filter(w=>wineTypes.includes(w.type));const max=Number(document.getElementById("priceRange")?.value||400);list=list.filter(w=>w.price<=max);const rating=Number(document.querySelector('input[name="rating"]:checked')?.value||0);if(rating)list=list.filter(w=>w.rating>=rating);const grapes=[...document.querySelectorAll(".grape-filter:checked")].map(x=>x.value);if(grapes.length)list=list.filter(w=>grapes.includes(w.grape));const sort=document.getElementById("sort")?.value;if(sort==="Menor preço")list.sort((a,b)=>a.price-b.price);if(sort==="Maior preço")list.sort((a,b)=>b.price-a.price);if(sort==="Melhor avaliação")list.sort((a,b)=>b.rating-a.rating);return list}
function renderCat(){if(!cat)return;const list=filters();cat.innerHTML=list.map(card).join("");const c=document.getElementById("resultCount");if(c)c.textContent="Exibindo 1-"+list.length+" de "+list.length+" VINHOS"}
document.querySelectorAll(".filters-panel input,#sort").forEach(x=>x.addEventListener("input",()=>{const r=document.getElementById("priceRange"),v=document.getElementById("priceValue");if(r&&v)v.textContent="R$0 – R$"+r.value;renderCat()}));renderCat();
const product=document.getElementById("product");if(product){const slug=new URLSearchParams(location.search).get("slug")||wines[0].slug;const w=wines.find(x=>x.slug===slug)||wines[0];product.innerHTML='<div class="product-grid"><div class="product-photo"><div class="big-bottle"><span>'+w.winery+'</span></div></div><div class="product-info"><div class="p-winery">'+w.winery+'</div><h1>'+w.name+'</h1><p>'+w.region+'</p><div class="p-rating">'+stars(w.rating)+' <small>('+w.reviews.toLocaleString("pt-BR")+' classificações)</small></div><div class="facts"><span><b>Tipo</b>'+w.type+'</span><span><b>Uva</b>'+w.grape+'</span><span><b>Região</b>'+w.region+'</span><span><b>Produtor</b>'+w.winery+'</span></div><div class="product-price">'+money(w.price)+'</div><button class="quote-btn product-quote" data-slug="'+w.slug+'">Pedir orçamento</button></div></div>';render("same",wines.filter(x=>x.winery===w.winery&&x.slug!==w.slug).concat(wines.filter(x=>x.winery!==w.winery)).slice(0,8));setupRails()}
