const wines=[
{slug:"santa-julia-chenin-dulce",winery:"Santa Julia",name:"Dulce Natural Chenin",region:"Mendoza, Argentina",grape:"Chenin Blanc",type:"Sobremesa",rating:4.1,reviews:78,price:89.9},
{slug:"dv-catena-chardonnay",winery:"D.V. Catena",name:"Chardonnay - Chardonnay",region:"Mendoza, Argentina",grape:"Chardonnay",type:"Branco",rating:4.2,reviews:22877,price:179.9},
{slug:"dv-catena-malbec",winery:"D.V. Catena",name:"Malbec - Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:4.2,reviews:18400,price:189.9},
{slug:"santa-julia-organica-malbec",winery:"Santa Julia",name:"Orgánica Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:3.8,reviews:91,price:99.9},
{slug:"santa-julia-la-vaquita",winery:"Santa Julia",name:"La Vaquita Clarete Natural",region:"Maipú, Argentina",grape:"Blend",type:"Rosé",rating:3.8,reviews:1417,price:109.9},
{slug:"santa-julia-el-zorrito",winery:"Santa Julia",name:"El Zorrito Naranjo Chardonnay",region:"Maipú, Argentina",grape:"Chardonnay",type:"Branco",rating:3.8,reviews:2511,price:119.9},
{slug:"catena-malbec",winery:"Catena Zapata",name:"Malbec",region:"Mendoza, Argentina",grape:"Malbec",type:"Tinto",rating:4.0,reviews:9820,price:159.9},
{slug:"chandon-brut",winery:"Chandon",name:"Brut",region:"Serra Gaúcha, Brasil",grape:"Blend",type:"Espumante",rating:4.0,reviews:3480,price:149.9}
];
const money=n=>"R$ "+n.toFixed(2).replace(".",",");
function card(w,i=0){return '<article class="premium-card"><a href="/vinho.html?slug='+encodeURIComponent(w.slug)+'"><div class="premium-card__image"><div class="premium-bottle"></div></div><div class="premium-card__meta"><small>'+w.winery.toUpperCase()+'</small><h3>'+w.name+'</h3><div class="price">'+money(w.price)+'</div></div></a><div class="premium-card__actions"><button class="buy-btn" data-slug="'+w.slug+'">Pedir orçamento</button><button class="mini-cart" aria-label="Adicionar">+</button></div></article>'}
function render(id,list){const el=document.getElementById(id);if(el)el.innerHTML=list.map(card).join("")}
render("offers",wines);render("malbecs",wines.filter(w=>w.grape==="Malbec").concat(wines).slice(0,8));
function rails(){document.querySelectorAll(".premium-rail-wrap,.rail-wrap").forEach(w=>{const rail=w.querySelector(".premium-rail,.product-rail");if(!rail)return;w.querySelector(".prev")?.addEventListener("click",()=>rail.scrollBy({left:-520,behavior:"smooth"}));w.querySelector(".next")?.addEventListener("click",()=>rail.scrollBy({left:520,behavior:"smooth"}));let d=false,s=0,l=0;rail.addEventListener("pointerdown",e=>{d=true;s=e.clientX;l=rail.scrollLeft;rail.classList.add("dragging");rail.setPointerCapture(e.pointerId)});rail.addEventListener("pointermove",e=>{if(d)rail.scrollLeft=l-(e.clientX-s)});["pointerup","pointercancel","pointerleave"].forEach(ev=>rail.addEventListener(ev,()=>{d=false;rail.classList.remove("dragging")}))})}
document.addEventListener("click",e=>{const b=e.target.closest(".buy-btn,.product-quote");if(!b)return;const slug=b.dataset.slug;const w=wines.find(x=>x.slug===slug);if(!w)return;window.open("https://wa.me/?text="+encodeURIComponent("Olá! Gostaria de solicitar um orçamento para "+w.winery+" "+w.name+"."),"_blank","noopener")});
const catalog=document.getElementById("catalog");function filtered(){let list=[...wines];if(!catalog)return list;const qs=new URLSearchParams(location.search);const q=(qs.get("q")||"").toLowerCase();if(q)list=list.filter(w=>[w.name,w.winery,w.region,w.grape,w.type].join(" ").toLowerCase().includes(q));const checked=[...document.querySelectorAll('.filters-panel input[type="checkbox"]:checked')].map(x=>x.value);const types=checked.filter(v=>["Tinto","Branco","Espumante","Rosé","Sobremesa","Fortificado"].includes(v));if(types.length)list=list.filter(w=>types.includes(w.type));const grapes=checked.filter(v=>["Cabernet Sauvignon","Malbec","Pinot Noir","Carménère","Shiraz/Syrah","Cabernet Franc","Primitivo","Tannat","Sangiovese","Tempranillo"].includes(v));if(grapes.length)list=list.filter(w=>grapes.includes(w.grape));const max=Number(document.getElementById("priceRange")?.value||9999);list=list.filter(w=>w.price<=max);const rat=Number(document.querySelector('input[name="rating"]:checked')?.value||0);if(rat)list=list.filter(w=>w.rating>=rat);const sort=document.getElementById("sort")?.value;if(sort==="Menor preço")list.sort((a,b)=>a.price-b.price);if(sort==="Maior preço")list.sort((a,b)=>b.price-a.price);if(sort==="Melhor avaliação")list.sort((a,b)=>b.rating-a.rating);return list}
function renderCatalog(){if(!catalog)return;const list=filtered();catalog.innerHTML=list.map(card).join("");const c=document.getElementById("resultCount");if(c)c.textContent="Exibindo "+list.length+" de "+list.length+" VINHOS"}
document.querySelectorAll(".filters-panel input,#sort").forEach(el=>el.addEventListener("input",()=>{const p=document.getElementById("priceRange"),v=document.getElementById("priceValue");if(p&&v)v.textContent="R$0 – R$"+p.value;renderCatalog()}));renderCatalog();
const product=document.getElementById("product");if(product){const slug=new URLSearchParams(location.search).get("slug")||wines[0].slug;const w=wines.find(x=>x.slug===slug)||wines[0];product.innerHTML='<div class="product-grid"><div class="gallery"><div class="thumb"></div><div class="product-image"><div class="big-bottle"><span>'+w.winery+'</span></div></div></div><div class="product-info"><span class="winery">'+w.winery+'</span><h1>'+w.name+'</h1><p class="product-region">'+w.region+'</p><div class="product-rating">★ '+w.rating.toFixed(1).replace(".",",")+' <span>('+w.reviews.toLocaleString("pt-BR")+' avaliações)</span></div><div class="facts"><div><b>Tipo</b><span>'+w.type+'</span></div><div><b>Uva</b><span>'+w.grape+'</span></div><div><b>Região</b><span>'+w.region+'</span></div><div><b>Produtor</b><span>'+w.winery+'</span></div></div><p class="description">Rótulo de demonstração para o catálogo Videira. Consulte disponibilidade, safra e condições comerciais no orçamento.</p><div class="product-price">'+money(w.price)+'</div><button class="product-quote" data-slug="'+w.slug+'">Pedir orçamento</button></div></div>';render("same",wines.filter(x=>x.winery===w.winery&&x.slug!==w.slug).concat(wines.filter(x=>x.winery!==w.winery)).slice(0,7))}
const slides=[...document.querySelectorAll(".premium-hero .hero-slide")],dots=[...document.querySelectorAll(".premium-hero .hero-dots button")];let current=0,timer;function show(i){current=i;slides.forEach((s,n)=>s.classList.toggle("active",n===i));dots.forEach((d,n)=>d.classList.toggle("active",n===i))}function auto(){clearInterval(timer);if(slides.length)timer=setInterval(()=>show((current+1)%slides.length),5500)}dots.forEach((d,i)=>d.addEventListener("click",()=>{show(i);auto()}));auto();rails();